version: '3'
services:
  flask:
    build: .
    ports:
      - "8079:8079"
    volumes:
      - /dev:/dev
      - ./music:/app/src/music
    privileged: true
    stop_signal: SIGINT
    depends_on:
      - database
    restart: always
    networks:
      - local
  database:
    image: postgres
    restart: always
    networks:
      - local
    environment: 
      POSTGRES_USER:      test
      POSTGRES_PASSWORD:  keystore #${DATABASE_PASSWORD}
      # POSTGRES_DB:        rpimidi
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

networks:
  local:
    driver: bridge
